In [1]:
import json as json
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import metrics
import numpy as np
from datetime import datetime

In [2]:
#cleaned data einlesen

srcDir = '/Users/jloy/OneDrive/Desktop/Unterlagen Johannes/Uni/Master/01_Semester I/Business Data Analytics - Applications and Tools/Data/'
inputStringCleaned = srcDir +'cleaned_data_unix.csv'
df = pd.read_csv(inputStringCleaned)
df['id2'] = df['id'] #id geht beim joinen verloren, daher sicherheitskopie
df['id3'] = df['id'] #id geht beim joinen verloren, daher sicherheitskopie
df

,id,deveui,unix_time,created_at,decoded_data.sensor_data.Events,decoded_data.sensor_data.Height 1,decoded_data.sensor_data.Temperature,decoded_data.sensor_data.Tilt,decoded_data.sensor_data.Tx Event,id2,id3
0,4110576,70B3D500700016DA,1620498360377,2021-05-08 20:26:00.596017,SENS_EVENT_MEASURE,112,14,1,193,4110576,4110576
1,4110093,70B3D500700016DA,1620494765501,2021-05-08 19:26:05.713448,SENS_EVENT_MEASURE,112,17,1,192,4110093,4110093
2,4109607,70B3D500700016DA,1620491158880,2021-05-08 18:25:59.323267,SENS_EVENT_MEASURE,108,15,0,191,4109607,4109607
3,4109118,70B3D500700016DA,1620487559091,2021-05-08 17:25:59.523137,SENS_EVENT_MEASURE,126,19,1,190,4109118,4109118
4,4108627,70B3D500700016DA,1620483959154,2021-05-08 16:25:59.577446,SENS_EVENT_MEASURE,118,20,0,189,4108627,4108627
...,...,...,...,...,...,...,...,...,...,...,...
515032,598759,70B3D50070001789,1588992614891,2020-05-09 04:50:15.056761,SENS_EVENT_MEASURE,104,19,5,142,598759,598759
515033,598510,70B3D50070001789,1588989015087,2020-05-09 03:50:15.256986,SENS_EVENT_MEASURE,104,19,4,141,598510,598510
515034,598261,70B3D50070001789,1588985415234,2020-05-09 02:50:15.408009,SENS_EVENT_MEASURE,104,19,5,140,598261,598261
515035,598017,70B3D50070001789,1588981815380,2020-05-09 01:50:15.558981,SENS_EVENT_MEASURE,86,19,5,139,598017,598017
515036,597775,70B3D50070001789,1588978215547,2020-05-09 00:50:15.726339,SENS_EVENT_MEASURE,86,22,7,138,597775,597775

In [3]:
#augmented Data einlesen
#zusÃ¤tzliche Spalten: is_holiday und rain in mm

inputStringAugmented = srcDir + 'augmented_data.csv'
df_augmented =  pd.read_csv(inputStringAugmented)
df_augmented.drop('deveui',1,inplace=True) #deveui raus
df_augmented

             id  is_holiday  rain (mm)
0       4110576           0        0.0
1       4110093           0        0.0
2       4109607           0        0.0
3       4109118           0        0.0
4       4108627           0        0.0
...         ...         ...        ...
515032   598759           0        0.0
515033   598510           0        0.0
515034   598261           0        0.0
515035   598017           0        0.0
515036   597775           0        0.0

[515037 rows x 3 columns]

In [4]:
print("The dataset df has", len(df['id'].unique()), "distinct ID's.")
print("The dataset df_augmented has", len(df_augmented['id'].unique()), "distinct ID's.")

The dataset df has 515037 distinct ID's.
The dataset df_augmented has 515037 distinct ID's.

In [5]:
df = df.set_index('id2').join(df_augmented.set_index('id'))
df

,id,deveui,unix_time,created_at,decoded_data.sensor_data.Events,decoded_data.sensor_data.Height 1,decoded_data.sensor_data.Temperature,decoded_data.sensor_data.Tilt,decoded_data.sensor_data.Tx Event,id3,is_holiday,rain (mm)
id2,,,,,,,,,,,,
4110576,4110576,70B3D500700016DA,1620498360377,2021-05-08 20:26:00.596017,SENS_EVENT_MEASURE,112,14,1,193,4110576,0,0.0
4110093,4110093,70B3D500700016DA,1620494765501,2021-05-08 19:26:05.713448,SENS_EVENT_MEASURE,112,17,1,192,4110093,0,0.0
4109607,4109607,70B3D500700016DA,1620491158880,2021-05-08 18:25:59.323267,SENS_EVENT_MEASURE,108,15,0,191,4109607,0,0.0
4109118,4109118,70B3D500700016DA,1620487559091,2021-05-08 17:25:59.523137,SENS_EVENT_MEASURE,126,19,1,190,4109118,0,0.0
4108627,4108627,70B3D500700016DA,1620483959154,2021-05-08 16:25:59.577446,SENS_EVENT_MEASURE,118,20,0,189,4108627,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
598759,598759,70B3D50070001789,1588992614891,2020-05-09 04:50:15.056761,SENS_EVENT_MEASURE,104,19,5,142,598759,0,0.0
598510,598510,70B3D50070001789,1588989015087,2020-05-09 03:50:15.256986,SENS_EVENT_MEASURE,104,19,4,141,598510,0,0.0
598261,598261,70B3D50070001789,1588985415234,2020-05-09 02:50:15.408009,SENS_EVENT_MEASURE,104,19,5,140,598261,0,0.0
598017,598017,70B3D50070001789,1588981815380,2020-05-09 01:50:15.558981,SENS_EVENT_MEASURE,86,19,5,139,598017,0,0.0
597775,597775,70B3D50070001789,1588978215547,2020-05-09 00:50:15.726339,SENS_EVENT_MEASURE,86,22,7,138,597775,0,0.0

In [6]:
#Increased Data einlesen
#zusÃ¤tzliche Spalten: delta time, delta hight

#Idee: die hight zu predicten macht ohne erklÃ¤rende Variable fÃ¼r die Entleerungen keinen Sinn (mehr oder weniger zufÃ¤lliges Ergebnis)
#da vorerst keine erklÃ¤rende Variable fÃ¼r Entleerung -> Entleerung normalisieren
#jetzt mÃ¼sste man noch entleerungen in increase erkennen und die werte enfernen (z.B. zu groÃŸes delta...)

inputStringIncrease = srcDir + 'data_with_increase.csv'
df_increase =  pd.read_csv(inputStringIncrease)
df_increase

,id,deveui,unix_time,decoded_data.sensor_data.Height 1,Time Delta (in ms),Hight Delta,Increase
0,597793,70B3D500700016DA,1588980000000,8,0,0,0.000000e+00
1,598036,70B3D500700016DA,1588980000000,8,3599808,0,0.000000e+00
2,598280,70B3D500700016DA,1588990000000,8,3599806,0,0.000000e+00
3,598530,70B3D500700016DA,1588990000000,8,3599831,0,0.000000e+00
4,598784,70B3D500700016DA,1588990000000,8,3599811,0,0.000000e+00
...,...,...,...,...,...,...,...
514858,4107194,70B3D50070001789,1620470000000,58,3599824,0,0.000000e+00
514859,4108624,70B3D50070001789,1620480000000,94,18003937,36,1.999560e-06
514860,4109602,70B3D50070001789,1620490000000,92,7194499,-2,-2.779900e-07
514861,4110089,70B3D50070001789,1620490000000,92,3601652,0,0.000000e+00
514862,4110570,70B3D50070001789,1620500000000,58,3600036,-34,-9.444350e-06

In [7]:
print("The dataset df has", len(df['id'].unique()), "distinct ID's.")
print("The dataset df_increase has", len(df_augmented['id'].unique()), "distinct ID's.")

The dataset df has 515037 distinct ID's.
The dataset df_increase has 515037 distinct ID's.

In [8]:
#UnnÃ¶tige Splaten rausschmeissen
df_increase.drop('deveui',1,inplace=True) #deveui raus
df_increase.drop('unix_time',1,inplace=True) # raus
df_increase.drop('decoded_data.sensor_data.Height 1',1,inplace=True) # raus
df_increase.drop('Time Delta (in ms)',1,inplace=True) # raus
df_increase.sort_values(by=['id'])

             id  Hight Delta      Increase
246789   597682            0  0.000000e+00
383040   597684            0  0.000000e+00
227528   597686            0  0.000000e+00
365518   597688            0  0.000000e+00
397954   597694            0  0.000000e+00
...         ...          ...           ...
507655  4111143            0  0.000000e+00
471493  4111145            2  2.778010e-07
358390  4111148            0  0.000000e+00
424295  4111163            0  0.000000e+00
493728  4111188            2  2.777900e-07

[514863 rows x 3 columns]

In [9]:
#spalten von object nach numeric casten
pd.to_numeric(df_increase['id'], errors='coerce')
#df_increase['Increase'] = df_increase['Increase;;;;;;;'].str.replace(';','')
#df_increase.drop('Increase;;;;;;;',1,inplace=True) # raus
df_increase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514863 entries, 0 to 514862
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           514863 non-null  int64
 1   Hight Delta  514863 non-null  int64
 2   Increase     514863 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 11.8 MB

In [10]:
df = df.set_index('id3').join(df_increase.set_index('id'))
df

,id,deveui,unix_time,created_at,decoded_data.sensor_data.Events,decoded_data.sensor_data.Height 1,decoded_data.sensor_data.Temperature,decoded_data.sensor_data.Tilt,decoded_data.sensor_data.Tx Event,is_holiday,rain (mm),Hight Delta,Increase
id3,,,,,,,,,,,,,
4110576,4110576,70B3D500700016DA,1620498360377,2021-05-08 20:26:00.596017,SENS_EVENT_MEASURE,112,14,1,193,0,0.0,0.0,0.000000e+00
4110093,4110093,70B3D500700016DA,1620494765501,2021-05-08 19:26:05.713448,SENS_EVENT_MEASURE,112,17,1,192,0,0.0,4.0,1.109070e-06
4109607,4109607,70B3D500700016DA,1620491158880,2021-05-08 18:25:59.323267,SENS_EVENT_MEASURE,108,15,0,191,0,0.0,-18.0,-5.000290e-06
4109118,4109118,70B3D500700016DA,1620487559091,2021-05-08 17:25:59.523137,SENS_EVENT_MEASURE,126,19,1,190,0,0.0,8.0,2.222260e-06
4108627,4108627,70B3D500700016DA,1620483959154,2021-05-08 16:25:59.577446,SENS_EVENT_MEASURE,118,20,0,189,0,0.0,-4.0,-2.777940e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
598759,598759,70B3D50070001789,1588992614891,2020-05-09 04:50:15.056761,SENS_EVENT_MEASURE,104,19,5,142,0,0.0,0.0,0.000000e+00
598510,598510,70B3D50070001789,1588989015087,2020-05-09 03:50:15.256986,SENS_EVENT_MEASURE,104,19,4,141,0,0.0,0.0,0.000000e+00
598261,598261,70B3D50070001789,1588985415234,2020-05-09 02:50:15.408009,SENS_EVENT_MEASURE,104,19,5,140,0,0.0,18.0,5.000200e-06
598017,598017,70B3D50070001789,1588981815380,2020-05-09 01:50:15.558981,SENS_EVENT_MEASURE,86,19,5,139,0,0.0,0.0,0.000000e+00
597775,597775,70B3D50070001789,1588978215547,2020-05-09 00:50:15.726339,SENS_EVENT_MEASURE,86,22,7,138,0,0.0,0.0,0.000000e+00

In [11]:
#Zeitliche Analyse hinzufÃ¼gen

df['parsed_time_month'] = pd.DatetimeIndex(df['created_at']).month
df['parsed_time_year'] = pd.DatetimeIndex(df['created_at']).year
df['parsed_time_week'] = pd.DatetimeIndex(df['created_at']).week
df['parsed_time_weekday'] = pd.DatetimeIndex(df['created_at']).weekday
df['parsed_time_unix'] = pd.DatetimeIndex(df['created_at']).astype(np.int64)
df.drop('created_at',1,inplace=True)
df

,id,deveui,unix_time,decoded_data.sensor_data.Events,decoded_data.sensor_data.Height 1,decoded_data.sensor_data.Temperature,decoded_data.sensor_data.Tilt,decoded_data.sensor_data.Tx Event,is_holiday,rain (mm),Hight Delta,Increase,parsed_time_month,parsed_time_year,parsed_time_week,parsed_time_weekday,parsed_time_unix
id3,,,,,,,,,,,,,,,,,
4110576,4110576,70B3D500700016DA,1620498360377,SENS_EVENT_MEASURE,112,14,1,193,0,0.0,0.0,0.000000e+00,5,2021,18,5,1620505560596017000
4110093,4110093,70B3D500700016DA,1620494765501,SENS_EVENT_MEASURE,112,17,1,192,0,0.0,4.0,1.109070e-06,5,2021,18,5,1620501965713448000
4109607,4109607,70B3D500700016DA,1620491158880,SENS_EVENT_MEASURE,108,15,0,191,0,0.0,-18.0,-5.000290e-06,5,2021,18,5,1620498359323267000
4109118,4109118,70B3D500700016DA,1620487559091,SENS_EVENT_MEASURE,126,19,1,190,0,0.0,8.0,2.222260e-06,5,2021,18,5,1620494759523137000
4108627,4108627,70B3D500700016DA,1620483959154,SENS_EVENT_MEASURE,118,20,0,189,0,0.0,-4.0,-2.777940e-07,5,2021,18,5,1620491159577446000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598759,598759,70B3D50070001789,1588992614891,SENS_EVENT_MEASURE,104,19,5,142,0,0.0,0.0,0.000000e+00,5,2020,19,5,1588999815056761000
598510,598510,70B3D50070001789,1588989015087,SENS_EVENT_MEASURE,104,19,4,141,0,0.0,0.0,0.000000e+00,5,2020,19,5,1588996215256986000
598261,598261,70B3D50070001789,1588985415234,SENS_EVENT_MEASURE,104,19,5,140,0,0.0,18.0,5.000200e-06,5,2020,19,5,1588992615408009000
598017,598017,70B3D50070001789,1588981815380,SENS_EVENT_MEASURE,86,19,5,139,0,0.0,0.0,0.000000e+00,5,2020,19,5,1588989015558981000
597775,597775,70B3D50070001789,1588978215547,SENS_EVENT_MEASURE,86,22,7,138,0,0.0,0.0,0.000000e+00,5,2020,19,5,1588985415726339000

In [12]:
#One-Hot encoding der kathegorischen Werte in Spalte DEVEUI
df_one_hot_id = pd.get_dummies(df.deveui,prefix='DEVEUI')
df = pd.concat([df,df_one_hot_id],axis=1)
df.drop('deveui',1,inplace=True) #originales ID-Feld raus
df

,id,unix_time,decoded_data.sensor_data.Events,decoded_data.sensor_data.Height 1,decoded_data.sensor_data.Temperature,decoded_data.sensor_data.Tilt,decoded_data.sensor_data.Tx Event,is_holiday,rain (mm),Hight Delta,...,DEVEUI_70B3D50070001777,DEVEUI_70B3D50070001779,DEVEUI_70B3D5007000177C,DEVEUI_70B3D50070001780,DEVEUI_70B3D50070001781,DEVEUI_70B3D50070001782,DEVEUI_70B3D50070001786,DEVEUI_70B3D50070001787,DEVEUI_70B3D50070001788,DEVEUI_70B3D50070001789
id3,,,,,,,,,,,,,,,,,,,,,
4110576,4110576,1620498360377,SENS_EVENT_MEASURE,112,14,1,193,0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4110093,4110093,1620494765501,SENS_EVENT_MEASURE,112,17,1,192,0,0.0,4.0,...,0,0,0,0,0,0,0,0,0,0
4109607,4109607,1620491158880,SENS_EVENT_MEASURE,108,15,0,191,0,0.0,-18.0,...,0,0,0,0,0,0,0,0,0,0
4109118,4109118,1620487559091,SENS_EVENT_MEASURE,126,19,1,190,0,0.0,8.0,...,0,0,0,0,0,0,0,0,0,0
4108627,4108627,1620483959154,SENS_EVENT_MEASURE,118,20,0,189,0,0.0,-4.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598759,598759,1588992614891,SENS_EVENT_MEASURE,104,19,5,142,0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
598510,598510,1588989015087,SENS_EVENT_MEASURE,104,19,4,141,0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
598261,598261,1588985415234,SENS_EVENT_MEASURE,104,19,5,140,0,0.0,18.0,...,0,0,0,0,0,0,0,0,0,1
598017,598017,1588981815380,SENS_EVENT_MEASURE,86,19,5,139,0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
597775,597775,1588978215547,SENS_EVENT_MEASURE,86,22,7,138,0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [13]:
df.to_csv(srcDir+'preprocessed_data_with_increase.csv', index=False)

# Bis hierhin Datenaufbereitung

# Folgend Regression

In [14]:
#Felder fÃ¼r features und label erstellen
df = df.dropna()


df_label = df['Increase']

df_features = df.copy()
df_features.drop('decoded_data.sensor_data.Height 1',1,inplace=True) # raus
df_features.drop('decoded_data.sensor_data.Events',1,inplace=True)
df_features.drop('unix_time',1,inplace=True)
df_features.drop('id',1,inplace=True)

print(df_features.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 514863 entries, 4110576 to 597775
Data columns (total 89 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   decoded_data.sensor_data.Temperature  514863 non-null  int64
 1   decoded_data.sensor_data.Tilt         514863 non-null  int64
 2   decoded_data.sensor_data.Tx Event     514863 non-null  int64
 3   is_holiday                            514863 non-null  int64
 4   rain (mm)                             514863 non-null  float64
 5   Hight Delta                           514863 non-null  float64
 6   Increase                              514863 non-null  float64
 7   parsed_time_month                     514863 non-null  int64
 8   parsed_time_year                      514863 non-null  int64
 9   parsed_time_week                      514863 non-null  int64
 10  parsed_time_weekday                   514863 non-null  int64
 11  parsed_time_unix                      514863 non-null  int64
 12  DEVEUI_70B3D500700016DA               514863 non-null  uint8
 13  DEVEUI_70B3D500700016DE               514863 non-null  uint8
 14  DEVEUI_70B3D500700016DF               514863 non-null  uint8
 15  DEVEUI_70B3D500700016E0               514863 non-null  uint8
 16  DEVEUI_70B3D500700016E5               514863 non-null  uint8
 17  DEVEUI_70B3D500700016E6               514863 non-null  uint8
 18  DEVEUI_70B3D500700016E7               514863 non-null  uint8
 19  DEVEUI_70B3D500700016EB               514863 non-null  uint8
 20  DEVEUI_70B3D500700016EE               514863 non-null  uint8
 21  DEVEUI_70B3D500700016F1               514863 non-null  uint8
 22  DEVEUI_70B3D500700016F2               514863 non-null  uint8
 23  DEVEUI_70B3D500700016F4               514863 non-null  uint8
 24  DEVEUI_70B3D500700016F6               514863 non-null  uint8
 25  DEVEUI_70B3D500700016F7               514863 non-null  uint8
 26  DEVEUI_70B3D500700016FA               514863 non-null  uint8
 27  DEVEUI_70B3D500700016FC               514863 non-null  uint8
 28  DEVEUI_70B3D50070001700               514863 non-null  uint8
 29  DEVEUI_70B3D50070001701               514863 non-null  uint8
 30  DEVEUI_70B3D50070001704               514863 non-null  uint8
 31  DEVEUI_70B3D50070001706               514863 non-null  uint8
 32  DEVEUI_70B3D50070001708               514863 non-null  uint8
 33  DEVEUI_70B3D50070001709               514863 non-null  uint8
 34  DEVEUI_70B3D5007000170F               514863 non-null  uint8
 35  DEVEUI_70B3D50070001710               514863 non-null  uint8
 36  DEVEUI_70B3D50070001712               514863 non-null  uint8
 37  DEVEUI_70B3D50070001713               514863 non-null  uint8
 38  DEVEUI_70B3D50070001714               514863 non-null  uint8
 39  DEVEUI_70B3D50070001715               514863 non-null  uint8
 40  DEVEUI_70B3D50070001716               514863 non-null  uint8
 41  DEVEUI_70B3D5007000171A               514863 non-null  uint8
 42  DEVEUI_70B3D5007000171E               514863 non-null  uint8
 43  DEVEUI_70B3D5007000171F               514863 non-null  uint8
 44  DEVEUI_70B3D50070001722               514863 non-null  uint8
 45  DEVEUI_70B3D50070001724               514863 non-null  uint8
 46  DEVEUI_70B3D50070001725               514863 non-null  uint8
 47  DEVEUI_70B3D50070001726               514863 non-null  uint8
 48  DEVEUI_70B3D50070001727               514863 non-null  uint8
 49  DEVEUI_70B3D5007000172B               514863 non-null  uint8
 50  DEVEUI_70B3D5007000172C               514863 non-null  uint8
 51  DEVEUI_70B3D5007000172D               514863 non-null  uint8
 52  DEVEUI_70B3D5007000172E               514863 non-null  uint8
 53  DEVEUI_70B3D50070001730               514863 non-null  uint8
 54  DEVEUI_70B3D50070001731               514863 non-null  uint8
 55  DEVEUI_70B3D50070001733               514863 non-null  uint8
 56  DEVEUI_70B3D50070001734               514863 non-null  uint8
 57  DEVEUI_70B3D50070001736               514863 non-null  uint8
 58  DEVEUI_70B3D50070001737               514863 non-null  uint8
 59  DEVEUI_70B3D50070001738               514863 non-null  uint8
 60  DEVEUI_70B3D50070001739               514863 non-null  uint8
 61  DEVEUI_70B3D5007000173A               514863 non-null  uint8
 62  DEVEUI_70B3D5007000173C               514863 non-null  uint8
 63  DEVEUI_70B3D5007000173E               514863 non-null  uint8
 64  DEVEUI_70B3D50070001740               514863 non-null  uint8
 65  DEVEUI_70B3D50070001742               514863 non-null  uint8
 66  DEVEUI_70B3D50070001743               514863 non-null  uint8
 67  DEVEUI_70B3D50070001747               514863 non-null  uint8
 68  DEVEUI_70B3D5007000174D               514863 non-null  uint8
 69  DEVEUI_70B3D5007000174F               514863 non-null  uint8
 70  DEVEUI_70B3D50070001750               514863 non-null  uint8
 71  DEVEUI_70B3D50070001759               514863 non-null  uint8
 72  DEVEUI_70B3D5007000175A               514863 non-null  uint8
 73  DEVEUI_70B3D5007000175E               514863 non-null  uint8
 74  DEVEUI_70B3D50070001764               514863 non-null  uint8
 75  DEVEUI_70B3D50070001766               514863 non-null  uint8
 76  DEVEUI_70B3D50070001770               514863 non-null  uint8
 77  DEVEUI_70B3D50070001772               514863 non-null  uint8
 78  DEVEUI_70B3D50070001774               514863 non-null  uint8
 79  DEVEUI_70B3D50070001777               514863 non-null  uint8
 80  DEVEUI_70B3D50070001779               514863 non-null  uint8
 81  DEVEUI_70B3D5007000177C               514863 non-null  uint8
 82  DEVEUI_70B3D50070001780               514863 non-null  uint8
 83  DEVEUI_70B3D50070001781               514863 non-null  uint8
 84  DEVEUI_70B3D50070001782               514863 non-null  uint8
 85  DEVEUI_70B3D50070001786               514863 non-null  uint8
 86  DEVEUI_70B3D50070001787               514863 non-null  uint8
 87  DEVEUI_70B3D50070001788               514863 non-null  uint8
 88  DEVEUI_70B3D50070001789               514863 non-null  uint8
dtypes: float64(3), int64(9), uint8(77)
memory usage: 88.9 MB
None

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df_features,df_label, test_size=0.2, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
print(regressor.intercept_)

2.6771208174432338e-05

In [17]:
print(regressor.coef_)

[ 3.65522734e-11 -6.70538342e-10  5.91193983e-11 -3.51927378e-11
  6.32757427e-11  2.43518631e-07  5.93144132e-14  5.67548765e-10
 -3.68561301e-11  5.60941088e-10 -3.46106601e-09 -1.66470098e-23
  6.28766794e-11 -7.34397612e-12  1.34096807e-11 -1.48287353e-11
  7.41663264e-12 -8.05764031e-12  1.03716363e-11 -1.88359147e-12
  1.85211091e-11  2.77803698e-12 -1.51055539e-11 -4.32414148e-12
 -9.94978072e-12 -9.27879507e-12 -1.87895954e-11 -3.44066150e-12
 -2.62695515e-12 -1.47372154e-11 -2.52973278e-12 -1.02720911e-11
 -1.25834897e-11 -1.09730368e-11 -1.02620771e-11  1.68366968e-11
 -6.30647038e-12 -3.59715601e-12  1.11321614e-11 -5.16094753e-12
  3.37229047e-11 -6.39805013e-12  3.70903841e-11 -1.18916916e-11
  6.51752337e-11 -6.97016215e-12  3.79157961e-11 -1.50047964e-11
 -8.27513909e-13  2.20444580e-11 -1.91107323e-11 -5.26780727e-12
 -2.55138308e-11 -9.06971053e-13 -2.19737927e-11 -1.05511700e-11
  1.08338941e-11 -8.04295727e-12 -5.96214111e-12 -2.94879372e-12
  2.70238184e-11  3.73210890e-12  4.53813839e-11 -2.26393942e-12
  1.44522197e-11 -2.41450329e-11 -5.70046537e-12 -8.40623321e-12
 -1.21687697e-11 -1.26507502e-11  1.86538809e-11 -1.67577300e-11
 -1.09867529e-11  3.81023942e-11 -1.06297503e-11 -9.97321103e-12
 -2.90464710e-11 -8.13621552e-12 -4.76699190e-12 -1.77670049e-11
 -9.89432648e-12 -1.07302035e-11 -1.19420367e-11  1.13183117e-11
 -9.28203054e-12  1.80815808e-11  3.05757185e-11 -1.07606178e-11
 -1.80161341e-11]

In [18]:
 y_pred = regressor.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

               Actual     Predicted
id3
2127155 -2.222350e-06 -1.885625e-06
2473502 -5.555970e-07 -4.655805e-07
1908936  0.000000e+00  7.765092e-08
2796594  5.555750e-07  4.916039e-07
2604252  0.000000e+00  5.710920e-09
...               ...           ...
3728203  0.000000e+00 -2.170840e-07
1431405  2.777950e-07  6.058369e-07
4100214  0.000000e+00 -2.701690e-07
3608041  0.000000e+00 -1.826982e-07
2626185  0.000000e+00  2.524819e-08

[102973 rows x 2 columns]

In [19]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 2.911865788282451e-07
Mean Squared Error: 1.1906740409536605e-12
Root Mean Squared Error: 1.0911801138921385e-06