In [1]:
import pandas as pd
import json as json
from pandas import json_normalize
import os
import csv
from matplotlib import pyplot as plt
import numpy as np

pd.options.mode.chained_assignment = None #Ignore Error: SettingWithCopyWarning

In [2]:
# Load cleaned data
srcDir = "../data/preprocessed/"
with open(srcDir + "cleaned_data_v6.csv", 'r') as f:
    data = list(csv.reader(f))

df = pd.DataFrame(data[1:], columns=data[0])
# df = df.drop(columns=["id", "messungszähler", "hight_increase", "tilt_in_grad"])

# deve_list = []
# for x in range(len(df.keys())):
#     if df.columns[x].startswith("DEVEUI"):
#         deve_list.append(x)

# df = df.drop(df.columns[deve_list], axis=1)
    
df

,height_delta,container_id,temperatur_in_grad,niederschlag_in_mm,ist_industriegebiet,ist_wohngebiet,ist_feiertag,datum,sekunde,minute,...,DEVEUI_70B3D50070001777,DEVEUI_70B3D50070001779,DEVEUI_70B3D5007000177C,DEVEUI_70B3D50070001780,DEVEUI_70B3D50070001781,DEVEUI_70B3D50070001782,DEVEUI_70B3D50070001786,DEVEUI_70B3D50070001787,DEVEUI_70B3D50070001788,DEVEUI_70B3D50070001789
0,0.0,77,0.33333334,0.0,0.0,1.0,0.0,2020-05-09 00:50:15.726339,0.2542373,0.84745765,...,0,0,0,0,0,0,0,0,0,1
1,0.0,77,0.28787878,0.0,0.0,1.0,0.0,2020-05-09 01:50:15.558981,0.2542373,0.84745765,...,0,0,0,0,0,0,0,0,0,1
2,0.0,77,0.28787878,0.0,0.0,1.0,0.0,2020-05-09 02:50:15.408009,0.2542373,0.84745765,...,0,0,0,0,0,0,0,0,0,1
3,0.0,77,0.28787878,0.0,0.0,1.0,0.0,2020-05-09 03:50:15.256986,0.2542373,0.84745765,...,0,0,0,0,0,0,0,0,0,1
4,0.0,77,0.28787878,0.0,0.0,1.0,0.0,2020-05-09 04:50:15.056761,0.2542373,0.84745765,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515032,0.10144926,1,0.3030303,0.0,0.0,1.0,0.0,2021-05-08 16:25:59.577446,1.0,0.42372882,...,0,0,0,0,0,0,0,0,0,0
515033,0.04347826,1,0.28787878,0.0,0.0,1.0,0.0,2021-05-08 17:25:59.523137,1.0,0.42372882,...,0,0,0,0,0,0,0,0,0,0
515034,0.1014493,1,0.22727273,0.0,0.0,1.0,0.0,2021-05-08 18:25:59.323267,1.0,0.42372882,...,0,0,0,0,0,0,0,0,0,0
515035,0.07246378,1,0.25757575,0.0,0.0,1.0,0.0,2021-05-08 19:26:05.713448,0.084745765,0.44067797,...,0,0,0,0,0,0,0,0,0,0
515036,0.03623189,1,0.21212122,0.0,0.0,1.0,0.0,2021-05-08 20:26:00.596017,0.0,0.44067797,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.keys().tolist()

['height_delta',
 'container_id',
 'temperatur_in_grad',
 'niederschlag_in_mm',
 'ist_industriegebiet',
 'ist_wohngebiet',
 'ist_feiertag',
 'datum',
 'sekunde',
 'minute',
 'stunde',
 'wochentag',
 'kalenderwoche',
 'monat',
 'jahr',
 'farbe_brown',
 'farbe_green',
 'farbe_white',
 'unix_time',
 'ist_ferien',
 'laengengrad',
 'breitengrad',
 'real_height',
 'smoothed_heigth',
 'year',
 'DEVEUI_70B3D500700016DA',
 'DEVEUI_70B3D500700016DE',
 'DEVEUI_70B3D500700016DF',
 'DEVEUI_70B3D500700016E0',
 'DEVEUI_70B3D500700016E5',
 'DEVEUI_70B3D500700016E6',
 'DEVEUI_70B3D500700016E7',
 'DEVEUI_70B3D500700016EB',
 'DEVEUI_70B3D500700016EE',
 'DEVEUI_70B3D500700016F1',
 'DEVEUI_70B3D500700016F2',
 'DEVEUI_70B3D500700016F4',
 'DEVEUI_70B3D500700016F6',
 'DEVEUI_70B3D500700016F7',
 'DEVEUI_70B3D500700016FA',
 'DEVEUI_70B3D500700016FC',
 'DEVEUI_70B3D50070001700',
 'DEVEUI_70B3D50070001701',
 'DEVEUI_70B3D50070001704',
 'DEVEUI_70B3D50070001706',
 'DEVEUI_70B3D50070001708',
 'DEVEUI_70B3D50070001709',
 'DEVEUI_70B3D5007000170F',
 'DEVEUI_70B3D50070001710',
 'DEVEUI_70B3D50070001712',
 'DEVEUI_70B3D50070001713',
 'DEVEUI_70B3D50070001714',
 'DEVEUI_70B3D50070001715',
 'DEVEUI_70B3D50070001716',
 'DEVEUI_70B3D5007000171A',
 'DEVEUI_70B3D5007000171E',
 'DEVEUI_70B3D5007000171F',
 'DEVEUI_70B3D50070001722',
 'DEVEUI_70B3D50070001724',
 'DEVEUI_70B3D50070001725',
 'DEVEUI_70B3D50070001726',
 'DEVEUI_70B3D50070001727',
 'DEVEUI_70B3D5007000172B',
 'DEVEUI_70B3D5007000172C',
 'DEVEUI_70B3D5007000172D',
 'DEVEUI_70B3D5007000172E',
 'DEVEUI_70B3D50070001730',
 'DEVEUI_70B3D50070001731',
 'DEVEUI_70B3D50070001733',
 'DEVEUI_70B3D50070001734',
 'DEVEUI_70B3D50070001736',
 'DEVEUI_70B3D50070001737',
 'DEVEUI_70B3D50070001738',
 'DEVEUI_70B3D50070001739',
 'DEVEUI_70B3D5007000173A',
 'DEVEUI_70B3D5007000173C',
 'DEVEUI_70B3D5007000173E',
 'DEVEUI_70B3D50070001740',
 'DEVEUI_70B3D50070001742',
 'DEVEUI_70B3D50070001743',
 'DEVEUI_70B3D50070001747',
 'DEVEUI_70B3D5007000174D',
 'DEVEUI_70B3D5007000174F',
 'DEVEUI_70B3D50070001750',
 'DEVEUI_70B3D50070001759',
 'DEVEUI_70B3D5007000175A',
 'DEVEUI_70B3D5007000175E',
 'DEVEUI_70B3D50070001764',
 'DEVEUI_70B3D50070001766',
 'DEVEUI_70B3D50070001770',
 'DEVEUI_70B3D50070001772',
 'DEVEUI_70B3D50070001774',
 'DEVEUI_70B3D50070001777',
 'DEVEUI_70B3D50070001779',
 'DEVEUI_70B3D5007000177C',
 'DEVEUI_70B3D50070001780',
 'DEVEUI_70B3D50070001781',
 'DEVEUI_70B3D50070001782',
 'DEVEUI_70B3D50070001786',
 'DEVEUI_70B3D50070001787',
 'DEVEUI_70B3D50070001788',
 'DEVEUI_70B3D50070001789']

In [8]:
df = df.drop(columns=["height_in_cm", "time_delta", "hight_delta"])
df.keys()

Index(['container_id', 'temperatur_in_grad', 'niederschlag_in_mm',
       'ist_industriegebiet', 'ist_wohngebiet', 'ist_feiertag', 'datum',
       'sekunde', 'minute', 'stunde', 'wochentag', 'kalenderwoche', 'monat',
       'jahr', 'farbe_brown', 'farbe_green', 'farbe_white', 'unix_time',
       'ist_ferien', 'laengengrad', 'breitengrad', 'real_height',
       'smoothed_heigth', 'smoothed_delta'],
      dtype='object')

In [20]:
# # Load cleaned data
# srcDir = "../data/preprocessed/"
# with open(srcDir + "cleaned_data_v3.csv", 'r') as f:
#     data = list(csv.reader(f))

# xx = pd.DataFrame(data[1:], columns=data[0])
# # xx = df.drop(columns=["id", "messungszähler", "hight_increase", "tilt_in_grad", ""])

# deve_list = []
# for x in range(len(xx.keys())):
#     if not xx.columns[x].startswith("laengengrad") and not xx.columns[x].startswith("breitengrad") and not xx.columns[x].startswith("container_id"):
#         deve_list.append(x)

# xx = xx.drop(xx.columns[deve_list], axis=1)
    
# xx

In [21]:
# join_list = []
# index = 1

# for x in range(len(xx)):
#     if xx["container_id"][x] == str(index):
#         join_list.append(xx.iloc[x].values)
#         index = index + 1
# join_list = pd.DataFrame(join_list, columns=xx.keys())

In [22]:
# join_list

In [23]:
# df = df.drop(columns=["laengengrad", "breitengrad"])
# df

In [24]:
# df = df.join(join_list.set_index('container_id'), on='container_id')
# df

In [25]:
# df.to_csv(os.path.join(srcDir, "cleaned_data_v6.csv"), index=False)

In [18]:
# year -> one-hot
year = pd.DataFrame({"jahr": ["2020", "2021"], "year" : ["0", "1"]})
year = year.astype({"jahr": "float32"})
df = df.join(year.set_index('jahr'), on='jahr')
df["year"]

0         0
1         0
2         0
3         0
4         0
         ..
515032    1
515033    1
515034    1
515035    1
515036    1
Name: year, Length: 515037, dtype: object

In [27]:
len(df)

515037

In [10]:
df.insert(0, "height_delta", df["smoothed_delta"])
df = df.drop(columns=["smoothed_delta"])
df

,height_delta,container_id,temperatur_in_grad,niederschlag_in_mm,ist_industriegebiet,ist_wohngebiet,ist_feiertag,datum,sekunde,minute,...,jahr,farbe_brown,farbe_green,farbe_white,unix_time,ist_ferien,laengengrad,breitengrad,real_height,smoothed_heigth
0,0.0,77,22,0,0,1,0,2020-05-09 00:50:15.726339,15,50,...,2020,0,1,0,1588980000000,0,50.1265414,8.6988155,54.0,54.0
1,0.0,77,19,0,0,1,0,2020-05-09 01:50:15.558981,15,50,...,2020,0,1,0,1588980000000,0,50.1265414,8.6988155,54.0,48.0
2,0.0,77,19,0,0,1,0,2020-05-09 02:50:15.408009,15,50,...,2020,0,1,0,1588990000000,0,50.1265414,8.6988155,36.0,42.0
3,0.0,77,19,0,0,1,0,2020-05-09 03:50:15.256986,15,50,...,2020,0,1,0,1588990000000,0,50.1265414,8.6988155,36.0,36.0
4,0.0,77,19,0,0,1,0,2020-05-09 04:50:15.056761,15,50,...,2020,0,1,0,1588990000000,0,50.1265414,8.6988155,36.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515032,4.666666,1,20,0,0,1,0,2021-05-08 16:25:59.577446,59,25,...,2021,0,0,1,1620480000000,0,50.13464,8.710139999999999,22.0,18.0
515033,2.0,1,19,0,0,1,0,2021-05-08 17:25:59.523137,59,25,...,2021,0,0,1,1620490000000,0,50.13464,8.710139999999999,14.0,22.666666
515034,4.666668,1,15,0,0,1,0,2021-05-08 18:25:59.323267,59,25,...,2021,0,0,1,1620490000000,0,50.13464,8.710139999999999,32.0,24.666666
515035,3.333334,1,17,0,0,1,0,2021-05-08 19:26:05.713448,5,26,...,2021,0,0,1,1620490000000,0,50.13464,8.710139999999999,28.0,29.333334
515036,1.666667,1,14,0,0,1,0,2021-05-08 20:26:00.596017,0,26,...,2021,0,0,1,1620500000000,0,50.13464,8.710139999999999,28.0,28.0

In [11]:
key_list = df.keys().tolist()

for x in range(len(key_list)):
    if not df.columns[x] == "datum":
        if not df.columns[x] == "container_id":
            df = df.astype({key_list[x]: "float32"})
    
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515037 entries, 0 to 515036
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   height_delta         515037 non-null  float32
 1   container_id         515037 non-null  object
 2   temperatur_in_grad   515037 non-null  float32
 3   niederschlag_in_mm   515037 non-null  float32
 4   ist_industriegebiet  515037 non-null  float32
 5   ist_wohngebiet       515037 non-null  float32
 6   ist_feiertag         515037 non-null  float32
 7   datum                515037 non-null  object
 8   sekunde              515037 non-null  float32
 9   minute               515037 non-null  float32
 10  stunde               515037 non-null  float32
 11  wochentag            515037 non-null  float32
 12  kalenderwoche        515037 non-null  float32
 13  monat                515037 non-null  float32
 14  jahr                 515037 non-null  float32
 15  farbe_brown          515037 non-null  float32
 16  farbe_green          515037 non-null  float32
 17  farbe_white          515037 non-null  float32
 18  unix_time            515037 non-null  float32
 19  ist_ferien           515037 non-null  float32
 20  laengengrad          515037 non-null  float32
 21  breitengrad          515037 non-null  float32
 22  real_height          515037 non-null  float32
 23  smoothed_heigth      515037 non-null  float32
dtypes: float32(22), object(2)
memory usage: 51.1+ MB

In [12]:
max(df["height_delta"])

46.0

In [13]:
# fetch [0,1]

def normalize(frame, name):
        min_v = abs(min(frame[name].tolist()))
        max_v = abs(max(frame[name].tolist()))
        
        final = 0
        
        if max_v > min_v:
            final = max_v
        else:
            final = min_v
        
        # already in (0,1) -> skip
        if final <= 1.0:
            return frame
        
        for x in range(len(frame[name])):
            frame[name][x] = frame[name][x] / final
        return frame

In [14]:
key_list = df.keys().tolist()
key_list.remove("ist_feiertag")
key_list.remove("ist_wohngebiet")
key_list.remove("ist_industriegebiet")
key_list.remove("datum")
key_list.remove("container_id")
key_list.remove("ist_ferien")
key_list

['height_delta',
 'temperatur_in_grad',
 'niederschlag_in_mm',
 'sekunde',
 'minute',
 'stunde',
 'wochentag',
 'kalenderwoche',
 'monat',
 'jahr',
 'farbe_brown',
 'farbe_green',
 'farbe_white',
 'unix_time',
 'laengengrad',
 'breitengrad',
 'real_height',
 'smoothed_heigth']

In [16]:
# normalize values

for x in range(len(key_list)):
    df = normalize(df, key_list[x])
    
df.head()

,height_delta,container_id,height_in_cm,temperatur_in_grad,niederschlag_in_mm,ist_industriegebiet,ist_wohngebiet,ist_feiertag,datum,sekunde,...,monat,jahr,farbe_brown,farbe_green,farbe_white,unix_time,time_delta,ist_ferien,laengengrad,breitengrad
0,0.000000,77,0.614286,0.333333,0.0,0.0,1.0,0.0,2020-05-09 00:50:15.726339,0.254237,...,0.416667,0.999505,0.0,1.0,0.0,0.980543,0.00000,0.0,0.99969,0.991806
1,0.000000,77,0.614286,0.287879,0.0,0.0,1.0,0.0,2020-05-09 01:50:15.558981,0.254237,...,0.416667,0.999505,0.0,1.0,0.0,0.980543,0.00034,0.0,0.99969,0.991806
2,0.134328,77,0.742857,0.287879,0.0,0.0,1.0,0.0,2020-05-09 02:50:15.408009,0.254237,...,0.416667,0.999505,0.0,1.0,0.0,0.980549,0.00034,0.0,0.99969,0.991806
3,0.000000,77,0.742857,0.287879,0.0,0.0,1.0,0.0,2020-05-09 03:50:15.256986,0.254237,...,0.416667,0.999505,0.0,1.0,0.0,0.980549,0.00034,0.0,0.99969,0.991806
4,0.000000,77,0.742857,0.287879,0.0,0.0,1.0,0.0,2020-05-09 04:50:15.056761,0.254237,...,0.416667,0.999505,0.0,1.0,0.0,0.980549,0.00034,0.0,0.99969,0.991806

In [17]:
df.to_csv(os.path.join(srcDir, "normalized_smoothed_data.csv"), index=False)